### ISSUE TITLE
Imports reference broken

### ISSUE THREAD

**Issue by AlistairB** [assemble/assemble-less#22]
Hi,

I updated from (i think) .5 to .7 and imports > reference stopped working

```
        less: {
            prod: {
                options: {
                    paths: styleLocation,
                    imports: {
                        reference: ["mixins.less", "variables.less", "images.less"]
                    },
                    syncImport: true
                },
                files: [{
                    expand: true,
                    cwd: styleLocation,
                    src: ["**/*.less", "!container.less", "!variables.less", "!mixins.less", "!**/external/*.less"],
                    dest: styleLocation + "/temp",
                    ext: ".css"
                }]
            }
        },
```

I have changed imports > less to imports > reference. But it wont compile because it can't find mixins in mixins.less.

Any ideas? Any way I can get more information on what is happening?

**Comment by MarcDiethelm** [comment]
So it's not just me doing something wrong. :) Confirmed.

**Comment by jonschlinkert** [comment]
Strange, sorry I don't know how I missed this issue. wasn't intentional. I'll look into it!

**Comment by jonschlinkert** [comment]
I've been trying to debug this, but it's working fine for me. I have a hunch that it has something to do with self-referencing files. Have you both tried using the feature with just a couple of files? that will help me know where to focus

**Comment by MarcDiethelm** [comment]
That's weird then. I just did some testing and reduced my case down to just two minimal files. One for reference use containing a single mixin definition. And one 'regular' src file. No import statements in either file.

``` css
less: {
    ref: {
        options: {
            imports: {
                reference : ['<%=tcBase%>/css/lib/reference/test.less']
            }
        }
        ,src  : '<%=tcBase%>/css/lib/test.less'
        ,dest: '<%=destCss%>/ref.css'
    }
}
```

But Less doesn't know about the mixin and aborts. I tried it with relative and absolute paths.
Did you already try to debug this with a assemble-less installed via npm? Not that it makes much sense. But maybe there's some subtle difference.
