### ISSUE TITLE
is it possible to not parse / exclude a custom syntax?

### ISSUE THREAD

**Issue by jackblackCH** [assemble/assemble-less#30]
the case I have is the framework skrollr. to work with stylesheets i need to add 

``` less
@-skrollr-keyframes animation-name {
  anchor-target {.welcome}
  top {
    opacity:0
  }
}
```

the less parser of course breaks at `anchor-target {.welcome}`

is there a way to get it work with a syntax like that. maybe to whitelist some syntax? for example whitelist @-my-custom-name { and everything here }
